version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: notification-postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/utils/database.sql:/docker-entrypoint-initdb.d/database.sql
    restart: always

  api:
    build: .
    container_name: notification-api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    restart: always
    command: npm run dev

volumes:
  postgres_data: